### ISSUE TITLE
Missing png/jpg files as output

### ISSUE THREAD

**Issue by adammach** [d3-node/d3node-linechart#10]
Hi,
I'm not sure if something is missing on my side, but as output I receive only svg and html files:
output(`./report_chart`, d3nLine({data: someData, isCurve: false}), { width: 960, height: 550 });

I'm using: "d3node-linechart":"^0.1.2"

**Comment by bradoyler** [comment]
yes, this:
`output('./report_chart', d3nLine({data: someData, isCurve: false}), { width: 960, height: 550 });`
should work fine.
Try the example in `./examples/index.js`

**Comment by adammach** [comment]
I think the problem is puppeteer (we're using docker). Maybe some info in wiki should be added?
