### ISSUE TITLE
Legend Help

### ISSUE THREAD

**Issue by Ronin11** [d3-node/d3node-linechart#6]
@geekplux 
When trying to add a simple legend to my graph it throws the following error:
TypeError: Cannot read property 'apply' of undefined
From the following location: d3-selection/build/d3-selection.js:500:11
```

svg.append('g')
        .attr('class','legend')
        .attr('transform','translate(50,30)')
	.style('font-size','12px')
	.call(d3.legend)
```

Any ideas what's going on?

**Comment by geekplux** [comment]
duplicated https://github.com/d3-node/d3-node/issues/28
