### ISSUE TITLE
Support for 2-line charts

### ISSUE THREAD

**Issue by khuongdv** [d3-node/d3node-linechart#7]
It is not actually an issue, I just want to know if this lib supports 2-line charts?

Example I have data in this format:

```
{
   data: [
         {
             Range: 'Jun 2018 - Jul 2018',
             ParentValue: 22,
             ChildValue: 32
         },
         //...
   ]
}
```
How can `d3node-linechart` generate a chart containing 2 lines corresponding to ParentValue and Child Value? (xAxis is the Range, of course).

Thanks.

**Comment by geekplux** [comment]
fixed by #8
